### ISSUE TITLE
Book structure suggestion

### ISSUE THREAD

**Issue by ColinFay** [DivadNojnarg/outstanding-shiny-ui#1]
Here is what I think would be a nice structure 

Part 1 — advance design

Html templates, JavaScript 

Part 2 — Engineering 

Modules and package 

Part 3 — scaling 

Future, promise, plumber, and everything related to asynchronous programming 

Part 4 — deploying 

Docker, shinyproxy, RStudio products (connect, shiny server), Kubernetes (maybe?), and any others. 
This part might also benefit from talking about packrat 

What do you think?

**Comment by DivadNojnarg** [comment]
> Here is what I think would be a nice structure
> 
> Part 1 — advance design
> 
> Html templates, JavaScript
> 
> Part 2 — Engineering
> 
> Modules and package
> 
> Part 3 — scaling
> 
> Future, promise, plumber, and everything related to asynchronous programming
> 
> Part 4 — deploying
> 
> Docker, shinyproxy, RStudio products (connect, shiny server), Kubernetes (maybe?), and any others.
> This part might also benefit from talking about packrat
> 
> What do you think?

@ColinFay 2 years later, each part has actually become an entire book :)
