### ISSUE TITLE
`parseInt()` base

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#100]
Should all (most) usage of `parseInt(x)` be converted to use base 10? I've been caught a couple of times where I sent in a value it the return value was not what I expected.

`parseInt(x, radix)`: The radix does not always default to 10. ... Always say `parseInt(x, 10)`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

**Comment by DivadNojnarg** [comment]
It does not cost much to specify the radix. Thanks!
