### ISSUE TITLE
Small but repeated language issue: 'allow to'

### ISSUE THREAD

**Issue by Jimbilben** [DivadNojnarg/outstanding-shiny-ui#109]
I'm going through chapter 1 at the moment, very excited to continue with the book! One thing to note - you repeatedly say 'allow to', e.g., 'Inline-block elements allow to insert block element in an inline.'. This is not major but to a native speaker I believe it sounds strange/incorrect. Instead of 'allow to', it should be 'Inline-block elements allow one to insert block element in an inline.', or differently: 'Inline-block elements allow the insertion of block elements in an inline.'.

**Comment by DivadNojnarg** [comment]
Thanks for reading the book. I believe the editor has a professional reader for language issues. For now the book was just reviewed from a "Content" point of view.

**Comment by Jimbilben** [comment]
The content is great! Good luck with the book
________________________________
