### ISSUE TITLE
Small bug in shiny code example in Chapter 1.3.5.2 HTML and JavaScript

### ISSUE THREAD

**Issue by Rudolf-May** [DivadNojnarg/outstanding-shiny-ui#112]
Hi, while working through the first chapter of your very helpful introduction I encountered a little bug in this shiny code example:
<code>
ui <- fluidPage(
  tags$script(
    "alert('Click on the Hello World text!');
     // change text color
     function changeColor(color){
       document.getElementById('hello').style.color = 'green';
     }
    "
  ),
  p(id = "hello", onclick="changeColor('green')", "Hello World")
)
server <- function(input, output, session) {}
shinyApp(ui, server)
</code>
Instead of:
document.getElementById('hello').style.color = 'green';
it should be:
document.getElementById('hello').style.color = color;

Best regards and thanx for your work!
Rudolf

**Comment by DivadNojnarg** [comment]
Thanks. This issue has been reintroduced in recent commit. I made a change and will push soon.
