### ISSUE TITLE
Confusing key command

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#33]
https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/758d81edc5fc583fe6778d37a173bc77d66b1524/web-intro.Rmd#L193

What should `Command + maj + C` be? I don't know what the combo is.

**Comment by DivadNojnarg** [comment]
On my mac it opens the google developer tools. Maybe it's easier with symbols instead: ⌥ + ⌘ + I

**Comment by schloerke** [comment]
I like the symbol approach. (So `maj` is `option` key?)

**Comment by DivadNojnarg** [comment]
My bad 🥇 , maj is the up left arrow but a french word for "Majuscule". It corresponds to the "shift" in english. I realised many different keys combo do the same thing. I'll refer to the symbols and the latest doc from the chrome developer tools.
