### ISSUE TITLE
Emily's review

### ISSUE THREAD

**Issue by DivadNojnarg** [DivadNojnarg/outstanding-shiny-ui#35]
To discuss with @emilyriederer

**Comment by emilyriederer** [comment]
Hi @DivadNojnarg ! Replying per your Twitter DM 🙂

**Comment by emilyriederer** [comment]
That makes sense to me, @DivadNojnarg !

**Comment by DivadNojnarg** [comment]
@schloerke, @rpodcast: @emilyriederer suggested a book rename sine the current one may be confusing. You may think the book will show how to develop oustanding interfaces using shiny, that is for instance how to master {shiny.fluent} or learn UX princip'es . Actually the book purpose is either to customize an existing shiny app with tools like {bslib},{sass}, {htmltools} or develop new widgets with JS ... Would you have ideas for an attractive title? Like "Customizing Shiny UI" ( i don't like it personally). Or an alternatice would be to add a quick part about UX design best practices and application to shiny using a specific template.

**Comment by DivadNojnarg** [comment]
I would like to avoid the latter since the book is already about 700 pages 😅

**Comment by emilyriederer** [comment]
I would definitely vote against adding more content! Even if you did, I think it's the current type of material that is most unique and valuable. A few thoughts (none of them particularly good, but just to start brainstorming):

- Advanced Shiny UI Development
- Building Outstanding Shiny UIs with the Modern Web Stack
- Developing custom Shiny UIs 
- Engineering outstanding Shiny interfaces (I don't like the "ing" "ing" of the first two words tho)

None of those are good, but I think one theme (for me at least), is I'm drawn to things that include some sort of word like "developing", "engineering", "building" that to me convey that the book is about how to do the technical "heavy lifting" versus names that just focus on the outcome which might sound more like a design book.

Just my two cents, but I definitely did not feel super strongly about that in my review! 🙂

**Comment by DivadNojnarg** [comment]
Could it just be `Outstanding User Interfaces for Shiny`? Just changing the `width` to `for`.

**Comment by rpodcast** [comment]
I fully admit that finding catchy titles (and by proxy naming variables) is not my strong suit, but after thinking for a bit I came up with these possibilities:
* Extending Shiny UIs: Beyond the Basics
* Propelling Shiny User Interfaces with Modern Tools
* Driving to an Outstanding Shiny UI

@DivadNojnarg 's suggestion above certainly could work too.

**Comment by DivadNojnarg** [comment]
`Extending Shiny UIs: Beyond the Basics`. Really like this one. Not too long and also self explanatory.

**Comment by schloerke** [comment]
Nice, @rpodcast !

`Extending Shiny UI: Beyond the Basics`
or 
`Extending Shiny UIs: Beyond the Basics`
?

... I'm a fan of the singular `UI`
