### ISSUE TITLE
Broken `shinydashboardPlus` demo app

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#38]
With the [latest version of `shinydashboardPlus` (>= 2.0.0)](https://rinterface.github.io/shinydashboardPlus/news/index.html#shinydashboardplus-2-0-0-2021-03-07), they removed the `dashboardPagePlus()` and `dashboardHeaderPlus()`.   (I could not easily adjust the demo for a PR.)

https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/4d2399043129c38dfd3f955941ccaf89a5647be6/htmltools-dependencies.Rmd#L321-L337

**Comment by DivadNojnarg** [comment]
Thanks. I'll take care
