### ISSUE TITLE
What is `InputBinding.getState()` used for?

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#50]
https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/758d81edc5fc583fe6778d37a173bc77d66b1524/shiny-input-system.Rmd#L508

@wch Is `getState()` within `InputBinding` only used within internal testing? I can see the tests were dropped in https://github.com/rstudio/shiny/commit/927972d889a663777a4259f288a3713053bd9f8e#diff-94f84001dccf0f461d37a3af30a3db5083cf05df0afcd8ca9123c56065d48f1f

(I had this question while converting the JS to TS. It didn't seem to hurt anything by having the methods and the values seemed sane, so I kept them.)

**Comment by wch** [comment]
Yes, I believe that the original motivation for `getState()` was for internal testing (though it's possible that there's something I'm not remembering).
