### ISSUE TITLE
Outdated demo code

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#52]
The CRAN versions of this application are both missing in `shinydashboardPlus` and `bs4Dash`. 

https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/525d2bcc8451009f23a6955729ef274272e7b8fa/shiny-input-system.Rmd#L1045-L1048

I could not easily fix the code.

**Comment by DivadNojnarg** [comment]
Strange. CRAN should be 2.0.0: https://github.com/RinteRface/shinydashboardPlus/tree/master/inst/vignettes-demos/box-api

**Comment by schloerke** [comment]
I think we can remove this line: https://github.com/RinteRface/shinydashboardPlus/blob/b8a36852a3be4d889748eb93d1a095a11efe9000/.Rbuildignore#L12

**Comment by DivadNojnarg** [comment]
Let me remember why I did this ;)

**Comment by DivadNojnarg** [comment]
Ok, that was a wrong .Rbuildignore entry. I'll push a CRAN patch for shinydashboardPlus and bs4Dash asap.

**Comment by DivadNojnarg** [comment]
SDB+ 2.0.2 is on its way to CRAN. Waiting for bs4Dash.
