### ISSUE TITLE
Shiny update input diagram

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#53]
Fig 13.3 diagram has some odd text formatting.

Minor changes I'd like to make:
* "Rather complex" -> "Complex"; Or remove
* "Modal, notifications" wraps "notifications" to two lines. Can it be fit into one?
* "Locates the good handler" -> "Locates a valid handler" or "Locates the correct handler"

**Comment by schloerke** [comment]
@DivadNojnarg Sorry for the unclear request...

Could the `Modal, notifications, ...` be

```
Modal,
notifications,
...
```
?

------------

Thank you for the other changes!

**Comment by DivadNojnarg** [comment]
Done!

**Comment by schloerke** [comment]
Thank you
