### ISSUE TITLE
Run code short cut commented before raw Shiny code

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#56]
I really enjoy having code that I can copy quickly and execute. Multi-line function definitions and larger chunks can quickly become difficult to follow.

I know this is more work, but if you could have a single function to be able to run the examples, that would be GREAT!

Something like...

```r
# OSUICode::run_example("name-foo-bar")
ui <- foo()
server <- bar()
shinyApp(ui, server)
```

To view the code, we could maybe supply a `view_code = TRUE` parameter (or something).

```
OSUICode::run_example("name-foo-bar", view_code = TRUE)
# returns output of `cat(paste0(readLines(app_r_to_name_foo_bar), collapse = "\n"), "\n")`
```

This would provide a consistent and quick way to get all examples and their code.

-------------------------------------------------

To avoid having examples in two locations, the chunk could be programmatically created!

Example within plumber...
Helper function to make a chunk: https://github.com/rstudio/plumber/blob/28bc58c19c44dceede023eeeb130708bd965d0eb/vignettes/_helpers.R#L8-L12
In action: https://github.com/rstudio/plumber/blob/28bc58c19c44dceede023eeeb130708bd965d0eb/vignettes/quickstart.Rmd#L40-L44
Output: https://www.rplumber.io/articles/quickstart.html#cb4
![Screen Shot 2021-07-05 at 10 35 51 PM](https://user-images.githubusercontent.com/93231/124534007-65c93f80-dde1-11eb-8d9f-28e3c3010f18.png)

**Comment by DivadNojnarg** [comment]
@schloerke: Based on your suggestion, I created a function that returns `code_chunk(run_example("dj-system"), "r", eval=FALSE)`:

```r
```{r, eval=FALSE}
### RUN ###: 
 OSUICode::run_example(system.file("dj-system", package = "OSUICode")) 
 
### APP CODE ### 
 library(shiny)
library(wavesurfer)

ui <- fluidPage(
  tags$head(
    tags$link(rel = "stylesheet", type = "text/css", href = "css/main.css"),
    tags$script(src = "js/main.js")
  ),
  tags$main(
    div(
      class = "screen",
        wavesurferOutput("my_ws")
    ),
    div(class = "jog paused"),
    div(class = "play action-button", id = "go"),
    div(class = "cue")
  )
)

server <- function(input, output, session) {
  output$my_ws <- renderWavesurfer({
    wavesurfer(audio = "music/track1.mp3", barHeight = 0.5) %>%
      ws_set_wave_color('#129cf5')
  })

  observeEvent(input$go, {
    if (input$go %% 2 != 0) {
      ws_play("my_ws")
    } else {
      ws_pause("my_ws")
    }

  })
}

shinyApp(ui, server) 
```
```

This will require a big rework but it's probably better solution to lighten the book from heavy examples.

**Comment by schloerke** [comment]
👏👏👏 This is exciting!

--------------------------

Small nit picks: 
* Add `sep = ""`. There is an odd space at the beginning of the `Run` and `App` code. 
* Is it possible to make `OSUICode::run_example(fullPath)` have the api of `OSUICode::run_example(file, package = "OSUICode")` (or `run_example(package, file)`)? I'd like to avoid the boiler plate of `system.file(package=)`. 
* Up to you... I'd comment the top part of the `Run` code to be separate from the `App` code. (Deter unexpected behavior when copy/pasting). 

Ex:

````
```{r, eval = FALSE}
## Run:
# OSUICode::run_example("dj-system")

### APP CODE ###
library(shiny)
library(wayvesurfer)
....
````

or even

````
```{r, eval = FALSE}
# OSUICode::run_example("dj-system")

library(shiny)
library(wayvesurfer)
....
````

------------------------

This feels too smooshed / loses the idea separation of `run_example()` and `library()` calls:

````
```{r, eval = FALSE}
# OSUICode::run_example("dj-system")
library(shiny)
library(wayvesurfer)
....
````

**Comment by DivadNojnarg** [comment]
```
```{r,eval=FALSE}
### RUN ### 
# OSUICode::run_example( 
#  "htmltools-deps-card/htmltools-deps-card-ex2" 
# ) 

### APP CODE ### 
library(shiny)
library(OSUICode)

bs4_cdn <- "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/"
bs4_css <- paste0(bs4_cdn, "css/bootstrap.min.css")

shinyApp(
  ui = fluidPage(
    # load the css code
    tags$head(
      tags$link(
        rel = "stylesheet",
        type = "text/css",
        href = bs4_css
      )
    ),
    fluidRow(
      column(
        width = 6,
        align = "center",
        br(),
        my_card("Card Content")
      )
    )
  ),
  server = function(input, output) {}
) 

```

Still need to carefully think how to rename all app folder and subfolders to avoid crazy long path.

**Comment by schloerke** [comment]
Looks great!

**Comment by DivadNojnarg** [comment]
![Screenshot 2021-08-19 at 19 01 18](https://user-images.githubusercontent.com/18291543/130111919-63b7b709-769e-4666-b66e-e38cc4b574b1.png)

**Comment by schloerke** [comment]
🥳

**Comment by DivadNojnarg** [comment]
A last comment. Do we agree that I don't treat/deploy such example? There are few in the book but this is quite trivial.
```r
library(shiny)
ui <- fluidPage()
server <- function(input, output, session) {}
shinyApp(ui, server)
```

**Comment by schloerke** [comment]
Agreed. Nothing to see / learn in the app.

**Comment by DivadNojnarg** [comment]
Just finished today.
