### ISSUE TITLE
Deploy all example application

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#57]
Similar to #56 , I'd LOVE to see all example applications in action.  The less that a user needs to do to discover the _feature_ or _idea_ of the app, the better!

-------------------------------------

If the applications were put into a `inst` folder, then they could be auto deployed by GHA and shipped within the package.

Ex: `learnr`

Folder of `tutorials` (which could be swapped out for shiny applications, ex: `./inst/examples/name-foo-bar/): https://github.com/rstudio/learnr/tree/dd9f145f7a9453644615e7844dbeaae5e46cdfc7/inst/tutorials

GHA to deploy applications: https://github.com/rstudio/learnr/blob/342723dd981091a742b75b67266158c91cb80afa/.github/workflows/R-CMD-check.yaml#L112-L185

Which eventually calls: https://github.com/rstudio/learnr/blob/dd9f145f7a9453644615e7844dbeaae5e46cdfc7/tools/deploy_tutorials_on_ci.R

Which could leverage `deploy_folder("inst/tutorials", deploy_app)`.

----------------------------------------------

While this would be some reorganizing, I believe this will be a lot **less** maintenance work for you and everything is read from the original, isolated source.

----------------------------------------------

Since the name is consistent when publishing to shinyapps.io, the link could be added into the chunk created by #56.  Ex:

```r
# App: https://OSUICode.shinyapps.io/name-foo-bar/
# Run: `OSUICode::run_example("name-foo-bar")`
library(shiny)
ui <- foo()
server <- bar()
shinyApp(ui, server)
```

**Comment by schloerke** [comment]
With everything automated, all applications can be passively deployed on each update to the book or to `OSUICode`. This is very beneficial to have both sets of information on the same set of information.

**Comment by schloerke** [comment]
It would also hide commented code like:

```r
# shinyAppDir(system.file(
#   "custom-handlers/add-message-item", 
#   package = "OSUICode"
# ))
```

... which could be reformatted to 

```r
OSUICode::run_example("custom-handlers-add-message-item")
```

**Comment by schloerke** [comment]
Images of the applications could be captured by `webshot2::appshot()` in a similar way that `appshot()` (which is calling `webshot::appshot()`) is used here: https://github.com/wch/webshot/blob/8cd235133e46cbce2d852521882524f94855e00e/vignettes/intro.Rmd#L104-L109

**Comment by DivadNojnarg** [comment]
@schloerke : does this mean `{shinytest}` will rely on `{webshot2}`?

**Comment by DivadNojnarg** [comment]
The reason I decided not to deploy anything is the long term support guaranty. I cannot say I'll be still doing R next year or later and the day I decide to stop, I'll also stop to maintain the RinteRface servers/shinyapps.io since it's expansive. There would be so many apps to deploy that I would need to pay at some point (shinyapps.io does not give more than 5 free deployments. We are probably talking about > 50 apps). Therefore, Github seems the most appropriate as you can have successors and the code will be there anyway. Maybe there are other free hosting solutions that would fit but I don't know.

**Comment by schloerke** [comment]
> shinyapps.io does not give more than 5 free deployments 

Boo. I did not know about the 5 free deployment limitation. Ok, the apps can stay on GitHub.

---------------------------------

> does this mean `{shinytest}` will rely on `{webshot2}`?

No. I'm working on a `{shinytest2}` which will rely on `{webshot2}`. `{shinytest}` / `{webshot}` will then go into maintenance mode. 

I'm hoping to have a `{testthat}` ed 3 interface that leverages their existing snapshot handling. Another motivator for moving to a new package is all snapshots would break moving from `phantomjs` to `chrome`.  Given two major changes, it makes sense to move to a new package.

---------------------------------

I'll close this issue in hopes that we can still get #56 to work.

**Comment by DivadNojnarg** [comment]
@schloerke : I am curious to see `{shinytest2}`, particularly if there will be an interface to plug custom templates, as shown in this issue: https://github.com/rstudio/shinytest/issues/369.

**Comment by schloerke** [comment]
That could be a funny quirk of phantomjs ({webshot}, {shinytest}). Let's hope the odd behavior just disappears when moving to Chrome ({chromote}, {webshot2}, {shinytest2}).

I'm guessing some JS didn't work properly which would cause the binding to never get made. I think there are more polyfills for PhantomJS 2.1 (browserslists treats it like Safari 6) than there are for IE11. 

🤞🤞

**Comment by schloerke** [comment]
I'm working with the Shiny team to get a shinyapps.io account to host examples for the book. Would this be ok?

Paired with your work in https://github.com/DivadNojnarg/outstanding-shiny-ui/issues/56#issuecomment-902084709 , it would work out well. The online book could have iframes to apps or an image with a link to the application. 

I'd be happy to help set up deployments when the time comes.

**Comment by DivadNojnarg** [comment]
Sounds great! Thats’s a fantastic proposition 🤩, thanks! Eventually, Automating all deployment would make life much easier for everyone. Let me know about the timing and if you need something else from my side.
