### ISSUE TITLE
Discourage using `shiny:::processDeps()`

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#58]
https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/525d2bcc8451009f23a6955729ef274272e7b8fa/shiny-custom-handler.Rmd#L158-L162

A handful of locations in this chapter you mention `shiny:::processDeps()`. I get uneasy when reaching into the private functions with such a public/permanent book.

I'd much rather see this be done with `htmltools::renderTags()`.  `$dep` is now `$singletons` and `$dependencies`.

Ex:

``` r
htmltools::renderTags(OSUICode:::dropdownMenu())
#> $head
#> 
#> 
#> $singletons
#> character(0)
#> 
#> $dependencies
#> $dependencies[[1]]
#> List of 9
#>  $ name      : chr "bs4-dropdown"
#>  $ version   : chr "1.0.0"
#>  $ src       :List of 1
#>   ..$ file: chr "/Library/Frameworks/R.framework/Versions/4.0/Resources/library/OSUICode/custom-handlers/add-message-item"
#>  $ meta      : NULL
#>  $ script    : chr "add-message-item.js"
#>  $ stylesheet: NULL
#>  $ head      : NULL
#>  $ attachment: NULL
#>  $ all_files : logi TRUE
#>  - attr(*, "class")= chr "html_dependency"
#> 
#> $dependencies[[2]]
#> List of 9
#>  $ name      : chr "font-awesome"
#>  $ version   : chr "5.15.3"
#>  $ src       :List of 1
#>   ..$ file: chr "/Library/Frameworks/R.framework/Versions/4.0/Resources/library/fontawesome/fontawesome"
#>  $ meta      : NULL
#>  $ script    : NULL
#>  $ stylesheet: chr [1:2] "css/all.min.css" "css/v4-shims.min.css"
#>  $ head      : NULL
#>  $ attachment: NULL
#>  $ all_files : logi TRUE
#>  - attr(*, "class")= chr "html_dependency"
#> 
#> 
#> $html
#> <li class="nav-item dropdown">
#>   <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
#>     <i class="fa fa-comments" role="presentation" aria-label="comments icon"></i>
#>     <span class="badge badge-primary navbar-badge">0</span>
#>   </a>
#>   <div class="dropdown-menu dropdown-menu-lg">
#>     <span class="dropdown-item dropdown-header">You have 0 messages</span>
#>     <div class="dropdown-divider"></div>
#>   </div>
#> </li>
```

<sup>Created on 2021-07-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by schloerke** [comment]
Or export `processDeps()` from `OSUICode` and state that you're using `OSUICode::processDeps(tags, session)` and not `shiny::processDeps(tags, session)`.

https://github.com/DivadNojnarg/outstanding-shiny-ui-code/blob/8115339756eb87539b8c53210418f83685359dd5/R/OSUICode-utils.R#L54


Chapter 20 instances:
* https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/ba9293faeb17d142bd5d83dfe0cc72e62c64ad88/custom-templates-interactivity.Rmd#L703-L704
* https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/ba9293faeb17d142bd5d83dfe0cc72e62c64ad88/custom-templates-interactivity.Rmd#L656-L662

**Comment by DivadNojnarg** [comment]
Thanks for raising this. I started the replacement. It works well and the change is minor: https://github.com/RinteRface/bs4Dash/commit/b2ca46cf64323999d03a785020184705e2b51b8c

**Comment by schloerke** [comment]
Thank you!

**Comment by DivadNojnarg** [comment]
@schloerke wondering if renderTags should also be documented in the htmltools chapter, for consistency reason and because I made the mistake to use processDeps too many times. It only appears in Chapter 5, then 15 and 20.

**Comment by schloerke** [comment]
The `htmltools` chapter, Chapter 2, mainly covers tags and tag manipulations. I think it can stay that way. 

Maybe it can be added in chapter 4, `Dependency utilities`? Specifically 4.5: Resolve dependencies.
