### ISSUE TITLE
Missing demo code - userMessages

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#59]
Similar to #52 

The CRAN versions of this application is missing in `shinydashboardPlus` 

https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/525d2bcc8451009f23a6955729ef274272e7b8fa/shiny-custom-handler.Rmd#L1002-L1007

I could not easily fix the code.

**Comment by DivadNojnarg** [comment]
Now that shinydashboardPlus 2.0.2 is on CRAN, I close the issue. I'll have to recompile the book with the good package reference.
