### ISSUE TITLE
Functions are not the same

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#66]
Original:
https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/d5c124f2edc70588d5a65d012004a8285fd0f044/custom-templates-skeleton.Rmd#L375-L394

Referenced:
https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/d5c124f2edc70588d5a65d012004a8285fd0f044/custom-templates-inputs.Rmd#L273-L298

--------------------

The Original uses `data-target` while the Referenced uses `href`.

(I like the white space of the Original)

**Comment by DivadNojnarg** [comment]
Thanks. `data-target` is the right one. Using `href` fails on shinyapps.io/rstudio connect (all resources using workers to spread the end-user load).
