### ISSUE TITLE
Chapter 20 uses a different `tabler_card()`

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#71]
`stacked` parameter was added and the code structure is different. Both look fine to me, just trying to have them be consistent.

Chapter 13 tabler:
https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/ba9293faeb17d142bd5d83dfe0cc72e62c64ad88/custom-templates-skeleton.Rmd#L532-L558

Chapter 20 tabler: (initial definition)
https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/ba9293faeb17d142bd5d83dfe0cc72e62c64ad88/custom-templates-testing.Rmd#L15-L42

**Comment by DivadNojnarg** [comment]
Thanks! I missed that part.
