### ISSUE TITLE
Chapter 24: Unknown config variable

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#78]
`config` in https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/ba9293faeb17d142bd5d83dfe0cc72e62c64ad88/mobile-shinyMobile.Rmd#L537 is not created until https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/ba9293faeb17d142bd5d83dfe0cc72e62c64ad88/mobile-shinyMobile.Rmd#L697

Mention somewhere close that `config` will be created later in the chapter. (Or move the creation up earlier. Up to you)

**Comment by DivadNojnarg** [comment]
I actually moved this section after the config definition and made minor edits.
