### ISSUE TITLE
No `app.data` in Framework7 6.0.0

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#79]
This is discouraging...
https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/ba9293faeb17d142bd5d83dfe0cc72e62c64ad88/mobile-shinyMobile.Rmd#L1085

Is there a _quick_ work around? Such as "Use `app.newData` instead."

**Comment by DivadNojnarg** [comment]
Forgot to specify and link to the alternative solution.
