### ISSUE TITLE
Can't undo prior `set_pwa()`

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#81]
Related: https://github.com/RinteRface/charpente/pull/15

For regular usage, you display the `set_pwa()` command. Then I run it. 
https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/ba9293faeb17d142bd5d83dfe0cc72e62c64ad88/mobile-pwa.Rmd#L67-L92

But for the application, we need an extra option to not register the service worker.  There are actions that the service worker code has taken that can not be undone by rerunning the command `set_pwa(..., register_service_worker = FALSE)` 
* `main.js` has the line of code `import './sw-register.js'
* `sw-register.js` exists.

I don't know how you'd like to approach this, but I feel into a trap that I think other will too.

**Comment by DivadNojnarg** [comment]
I removed the first occurence:

```r
set_pwa("inst/examples/pwa-app")
```

and only gave the shinyMobile solution so that user are not confused.

**Comment by schloerke** [comment]
Thank you!
