### ISSUE TITLE
Duplicate chapter name and chapter group divider

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#87]
While I understand the intent, the duplicate name gives me a little bit of confusion

Chapter 27 and the divider between 27 and 28 are both titled "Going further".

![Screen Shot 2021-07-11 at 11 19 49 AM](https://user-images.githubusercontent.com/93231/125200695-1c8e4b00-e23a-11eb-9ae0-a5838dfd2363.png)

Maybe retitle Chapter 27?

**Comment by DivadNojnarg** [comment]
I renamed it. Also there was only 1 section in that chapter. I think I initially wanted to add more use cases but did not find other interesting tips. I'll come back later if I have new ideas.
