### ISSUE TITLE
Chapter 28 difficulties

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#92]
I had a lot of trouble to get `argon-design-system-react` installed. It needs to be installed on Node v12.x . While only [released < 2 years ago](https://nodejs.org/en/blog/release/v12.13.0/) (4 lifetimes in JavaScript), Node > 12 can not install all of the packages requested in the chapter.

Related: https://github.com/creativetimofficial/argon-design-system-react/blob/e6948538f54deb21b58540adbdc7c030c85031e3/package.json#L55
Related: https://stackoverflow.com/questions/60394291/error-node-modules-node-sass-command-failed , https://www.npmjs.com/package/node-sass

When trying with Node v13.x
```
error icss-utils@5.1.0: The engine "node" is incompatible with this module. Expected version "^10 || ^12 || >= 14". Got "13.14.0"
```

The older version of `node-sass` also requires python 2.7. This requires an extra `.npmrc` that sets the python variable. 

```
python = "/usr/bin/python2.7"
```

The amount of special setup needed to perform the chapter's example seems like way too much work and is invasive to other projects. I'd point blame towards `argon-design-system-react` as it is using an outdated version of `node-sass`. However, the example still uses `argon-design-system-react`.

------------------------------------------------

I believe the quality of this chapter was not up to the quality and smoothness of the other chapters. It felt like I was jerked around. After working through the chapter, it felt like it was written when you were tired.

I fully acknowledge that it is **very** difficult to teach just enough R + JSX + webpack to be dangerous and to not get lost while developing the code.

Please take a look at Chapter 28 with a fresh pair of eyes and run through it as if you were a new user.

**Comment by DivadNojnarg** [comment]
This is annoying indeed. I keep this issue in standby until I fix everything else. Then I'll decide if I keep the chapter or not. Maybe with a more standard and simpler case study, semantic UI ...

**Comment by DivadNojnarg** [comment]
Hi @schloerke: do you manage to seamlessly install semantic ui react?

```
$  yarn add semantic-ui-react semantic-ui-css
## Or NPM
$  npm install semantic-ui-react semantic-ui-css
```

if no, are you OK with reactstrap?

```
npm install --save reactstrap react react-dom
```

**Comment by DivadNojnarg** [comment]
TO DO: add https://github.com/stla/shinyChakraUI
