### ISSUE TITLE
`tag_to_string()` might be a misrepresent that objects

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#97]
Within web-intro.Rmd, should the tags throughout the book be presented without calling `tag_to_string()`? It seems like that is a misrepresentation of what they actually are. While it formats nicely, it could be `cat()`ed to the screen instead of printed as a multiline `print()` string.

**Comment by DivadNojnarg** [comment]
@schloerke Do you think an approach like [this](https://github.com/rstudio/htmltools/blob/master/vignettes/tagQuery.Rmd#L16) would suit? I am worried about possible side effects in the book. There are some much code output to handle.

```r
registerS3method(
  "knit_print", "shiny.tag",
  getS3method("print", "shiny.tag")
)
registerS3method(
  "knit_print", "shiny.tag.list",
  getS3method("print", "shiny.tag.list")
)
```

**Comment by schloerke** [comment]
Should work? To be safe, you could also use `if (knitr::is_html_output()) { CODE }` to only add that logic for the website.

Ex: https://github.com/cpsievert/plotly_book/blob/43eac4be1fb0acb7f2d98dbc27de8e85c5b8a8bf/figure-refs.Rmd#L19
