### ISSUE TITLE
Missing peace sign for demo

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#99]
The "peace sign" character in demo to produce Figure 6.3 did not render for the book. (It works online.)

https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/ba9293faeb17d142bd5d83dfe0cc72e62c64ad88/beautify-css.Rmd#L539

Maybe using the unicode value will work? `"\u270c"` https://emojipedia.org/victory-hand/

**Comment by schloerke** [comment]
I don't believe this one is fixed. The `peace sign` character is still there. 

(If this is ok, please ignore)

**Comment by DivadNojnarg** [comment]
The online version is not updated yet. I am just editing the Rmd. In the Rmd I added `"OK"` instead of the character, since it is not very important.
